In [12]:
my_list=[1,2,3]
my_list1=(1,2,3)
my_list2={'x':1,'y':2,'z':3}
print("List 형식")
print (my_list)
type(my_list)
print("Tuple 형식")
print (my_list1)
type(my_list1)
print("dict 형식")
print (my_list2)
type(my_list2)

List 형식
[1, 2, 3]
Tuple 형식
(1, 2, 3)
dict 형식
{'x': 1, 'y': 2, 'z': 3}


dict

In [1]:
u=[2,2]
v=[2,3]
z=[3,5]
result=[]
result1=[]
for i in range(len(u)):
    result.append(u[i]+v[i]+z[i])
result1=[sum(t) for t in zip(u,v,z)]
print ("for append 사용")
print (result)
print ("Sum 사용")
print (result1)

u=[1,2,3]
v=[4,4,4]
alpha=2

result5 = [alpha*sum(t) for t in zip(u,v)]
print ("Sum과 가벼운 연산")
print (result5)

for append 사용
[7, 10]
Sum 사용
[7, 10]
Sum과 가벼운 연산
[10, 12, 14]


In [8]:
matrix_a = [[3,6],[4,5]]
print ("[3,6] \n[4,5]  표현식")
print (matrix_a)

[3,6] 
[4,5]  표현식
[[3, 6], [4, 5]]


In [20]:
matrix_a = [[3,6],[4,5]]
matrix_b = [[5,8],[6,7]]
result = [[sum(row) for row in zip(*t)] for t in zip(matrix_a,matrix_b)]
print ("이중 for문 사용\n[3,6]+[5,8]\n[4,5] [6,7]")
print (result)


이중 for문 사용
[3,6]+[5,8]
[4,5] [6,7]
[[8, 14], [10, 12]]


In [28]:
for t in zip(matrix_a,matrix_b):
    print (*t)

    

[3, 6] [5, 8]
[4, 5] [6, 7]


In [31]:
matrix_a = [[4,5],[1,2]]
alpha =4 
result = [[alpha * a for a in t] for t in matrix_a]
result

[[16, 20], [4, 8]]

In [6]:
import pandas as pd

data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data=pd.read_csv(data_url, sep='\s+',header = None)
df_data.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [19]:
df_data.columns = ['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98     1  
1     17.8  396.90   9.14     1  
2     17.8  392.83   4.03     1  
3     18.7  394.63   2.94     1  
4     18.7  396.90   5.33     1

In [12]:
import numpy as np

weight_vector = np.array([[1],[1],[1]])

print (weight_vector)

x_vector= np.array([[3],[4],[5]])

weight_vector.T.dot(x_vector)

[[1]
 [1]
 [1]]


array([[12]])

In [21]:
df_data['weight_0']=1
df_data=df_data.drop("MEDV",axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [31]:
'''df_matrix=df_data.as_matrix()
print (df_matrix)

weight_vector = np.random.random_sample((14,1))
print (weight_vector)

df_matrix.dot(weight_vector)'''



'df_matrix=df_data.as_matrix()\nprint (df_matrix)\n\nweight_vector = np.random.random_sample((14,1))\nprint (weight_vector)\n\ndf_matrix.dot(weight_vector)'

In [48]:
test_array = np.array([1,4,5,8],float)
test_array1 = np.array([1,4,5,8],np.float32)
print (test_array)
print (type (test_array[3]))

print ("\n64라는건 64비트의 플롯데이터까지 들어간다는 말이다.\nnumpy는 하나의 데이터 type만을 배열에 넣을 수 있음.")

print (test_array.dtype)
print (test_array1.dtype)


print ("Integer나 float 값만 일단은 사용한다")

a= np.array([[1,2,3],[4.5,5,6]], int)
print (a)
print (a[0,0])
print (a[0][0])



[ 1.  4.  5.  8.]
<class 'numpy.float64'>

64라는건 64비트의 플롯데이터까지 들어간다는 말이다.
numpy는 하나의 데이터 type만을 배열에 넣을 수 있음.
float64
float32
Integer나 float 값만 일단은 사용한다
[[1 2 3]
 [4 5 6]]
1
1


In [51]:
b= np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
print (b)
print (b[:,2:])
print (b[1,1:3])
print (b[1:3])
print ("범위를 넘어가면 그 전까지의값만 보여줌")



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]
범위를 넘어가면 그 전까지의값만 보여줌


In [1]:
k=np.arange(30)
print (type(k))
rk=np.arange(30).reshape(5,6)
print(rk)

NameError: name 'np' is not defined

In [5]:
import numpy as np
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [6]:
test_a +test_a

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [7]:
test_a -test_a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
#곱셈
A=test_a *test_a
print(A)
print("그냥 곱셈의 경우엔 동위치에 있는 값들만을 곱해준다.")

[[  1.   4.   9.]
 [ 16.  25.  36.]]
그냥 곱셈의 경우엔 동위치에 있는 값들만을 곱해준다.


In [18]:
test_a.T.dot(test_a)

array([[ 17.,  22.,  27.],
       [ 22.,  29.,  36.],
       [ 27.,  36.,  45.]])

In [19]:
test_a.dot(test_a.T)

array([[ 14.,  32.],
       [ 32.,  77.]])

In [ ]:
test_a.transpose()

In [13]:
#트랜스포즈 (항상 트랜스포즈 후엔 할당을 해주어야한다. 해주지 않으면 저장 안됨)
test_a.T

array([[ 1.,  4.],
       [ 2.,  5.],
       [ 3.,  6.]])

In [40]:
test_matrix=np.array([[1,2,3],[4,5,6]], float)
scalar =5

In [41]:
test_matrix+scalar

array([[  6.,   7.,   8.],
       [  9.,  10.,  11.]])

In [42]:
test_matrix-scalar

array([[-4., -3., -2.],
       [-1.,  0.,  1.]])

In [43]:
test_matrix*scalar

array([[-4., -3., -2.],
       [-1.,  0.,  1.]])

In [44]:
test_matrix/scalar

array([[-4., -3., -2.],
       [-1.,  0.,  1.]])

In [45]:
test_matrix//scalar #몫을 구하는 경우

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  1.]])

In [46]:
test_matrix**scalar

array([[  1.00000000e+00,   3.20000000e+01,   2.43000000e+02],
       [  1.02400000e+03,   3.12500000e+03,   7.77600000e+03]])

# ※ Numpy Boolean Index
(Boolean으로 선별 가능한 조건을 선언해줘야한다.)

In [49]:
#테스트 어레이 선언
test_array = np.array([1,4,0,2,3,8,9,7],float)

# 3 보다 큰 것을 찾아라!
test_array > 3

array([False,  True, False, False, False,  True,  True,  True], dtype=bool)

In [50]:
# 위와는 다르게 조건에 맞는 애들만 추출해라
test_array[test_array>3]

array([ 4.,  8.,  9.,  7.])

In [51]:
condition =test_array <3
test_array[condition]

array([ 1.,  0.,  2.])

# ※ Numpy fancy index
(interger타입으로 선언해줘야한다.)

In [52]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,1,3,2,1],int) #int 값으로 선언하여서 인덱스로써 사용
a[b] 
#bracket index a의 인덱스 값들을 b인트만큼 뽑아내라 , 인덱스값 넘어가면 안나옴
#bracket = 괄호 라는 뜻

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [53]:
a.take(b) #take 함수 bracket index와 같은 함수

array([ 2.,  2.,  4.,  8.,  6.,  4.])

In [54]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] #b를 row index, c를 column index로 변환하여 표시함 

array([  1.,   4.,  16.,  16.,   4.])

# ※ Numpy linear algebra

In [56]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [61]:
c = np.linalg.solve(a, b)
c

array([ 2.,  3.])

In [1]:
a.dot(c.T)

NameError: name 'a' is not defined

In [3]:
import numpy as np
x = np.array([9/14,5/14])
x

array([ 0.64285714,  0.35714286])

In [4]:
y = np.log2(x)
y

array([-0.63742992, -1.48542683])

In [5]:
-sum(x * y)

0.94028595867063114